# Generated by Django 5.2.3 on 2025-06-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
