# Generated by Django 5.2.3 on 2025-06-26 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_shipment_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
